services:
  - type: web
    name: ddd
    env: python
    buildCommand: |
      apt-get update &&
      apt-get install -y tesseract-ocr poppler-utils &&
      pip install -r requirements.txt
    startCommand: gunicorn server.app:app
